on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: "1"
  REGISTRY: sample.azurecr.io     # TODO: Replace the registry name with your own
  IMAGE: app

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - run: cargo build
    - run: cargo clippy
    - run: cargo test

    - run: docker build -t $REGISTRY/$IMAGE:$GITHUB_SHA .
